[package]
name = "dragonfly/ecosystem"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"
testez = "roblox/testez@0.4.1"
maid = "devsparkle/maid@2.0.0"
cmdr = "evaera/cmdr@1.9.0"
promise = "evaera/promise@4.0.0"